l_spanish:
 
 is_your_child_desc: "È tuo/a figlio/a"
 is_your_close_family_desc: "È un Parente Stretto"
 is_your_house_desc: "È della tua Casata"
 landed_spouse_desc: "Un Coniuge con un Territorio"
 landed_heir_desc: "Un Erede con un Territorio"
 has_many_good_relations_desc: "Ha Molti Amici"
 has_many_bad_relations_desc: "È Ostacolato dai Rivali"
 part_of_feud_desc: "Parte di una Faida"
 high_diplomacy_desc: "Un Alto livello di Diplomazia"
 high_martial_desc: "Un Alto livello di Marzialità"
 high_stewardship_desc: "Un Alto livello di Gestione"
 high_intrigue_desc: "Un Alto livello di Intrigo"
 high_learning_desc: "Un Alto livello di Istruzione"
 high_prowess_desc: "Un Alto livello di Prodezza"
 high_education_desc: "È Altamente Istruito"
 more_beautiful_desc: "Ha una Bellezza superiore all'Erede"
 more_smart_desc: "Ha un'Intelligenza superiore all'Erede"
 more_fit_desc: "È più Adatto dell'Erede"
 more_strong_desc: "È più Forte dell'Erede"
 more_skillful_desc: "È più Abile dell'Erede"
 has_nickname_desc: "Ha un Soprannome"
 more_famous_desc: "Più Famoso dell'Erede"
 second_in_line_desc: "Secondo in Linea di Successione"
 higher_title_desc: "Detiene un Titolo Superiore"
 new_liege_desc: "Sarebbe Sotto un Nuovo Signore"
 new_top_liege_desc: "Sarebbe sotto l'Autorità di un Signore Supremo"
 tall_claims_desc: "Detiene Rivendicazioni Importanti"
 pressed_claims_desc: "Detiene Rivendicazioni Reclamate"
 unpressed_claims_desc: "Detiene Rivendicazioni non Reclamate"
 inheritance_line_desc: "In linea di Successione"
 has_interesting_story_desc: "Ha una Storia Interessante"
 child_of_destiny_desc: "È un Figlio del Destino"
 virtues_interesting_desc: "Ha Tratti Virtuosi"
 tourney_xp_desc: "[GetTrait('tourney_participant').GetName( GetNullCharacter )] con Esperienza"
 reveler_xp_desc: "[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )] con Esperienza"
 mystic_xp_desc: "Esperienza come [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 hunter_xp_desc: "[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )] con Esperienza"
 blademaster_xp_desc: "[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )] con Esperienza"
 traveler_xp_desc: "[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )] con Esperienza"
 physician_xp_desc: "[GetTrait('lifestyle_physician').GetName( GetNullCharacter )] con Esperienza"
 herbalist_xp_desc: "[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )] con Esperienza"
 loyal_interesting_desc: "È [GetTrait('loyal').GetName( GetNullCharacter )]"
 disloyal_interesting_desc: "È [GetTrait('disloyal').GetName( GetNullCharacter )]"
 faith_warrior_interesting_desc: "È un [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc: "Hs il [GetTrait('blood_of_prophet').GetName( GetNullCharacter )]"
 varangian_interesting_desc: "È un [GetTrait('varangian').GetName( GetNullCharacter )]"
 poet_interesting_desc: "È un [GetTrait('poet').GetName( GetNullCharacter )]"
 peasant_leader_interesting_desc: "È un [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 populist_leader_interesting_desc: "È un [GetTrait('populist_leader').GetName( GetNullCharacter )]"
 berserker_interesting_desc: "È un [GetTrait('berserker').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc: "È [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 scaly_interesting_desc: "Ha [GetTrait('scaly').GetName( GetNullCharacter )]"
 albino_interesting_desc: "È un [GetTrait('albino').GetName( GetNullCharacter )]"
 dwarf_interesting_desc: "È un [GetTrait('dwarf').GetName( GetNullCharacter )]"
 giant_interesting_desc: "È un [GetTrait('giant').GetName( GetNullCharacter )]"
 devoted_interesting_desc: "È un [GetTrait('devoted').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc: "È [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "È un [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "È [GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc: "È [GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc: "È un Diarca"
 ruler_in_foreign_lands_interesting_desc: "È un Sovrano in Terra Straniera"
 valiant_knight_interesting_desc: "È un Cavaliere Valoroso"
 sinful_bastard_interesting_desc: "È un [GetTrait('bastard').GetName( GetNullCharacter )] peccaminoso"
 adventurer_interesting_desc: "È un Avventuriero"
 liege_crusader_king_liege_lineage_interesting_desc: "Signore della Stirpe del [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 holy_site_steward_interesting_desc: "La Capitale è un Luogo Sacro"
 has_a_legend_interesting_desc: "Ha una Leggenda"
 weak_hook_liege_interesting_desc: "Ha un Gancio Debole sul Signore"
 strong_hook_liege_interesting_desc: "Ha un Gancio Forte sul Signore"
 beloved_by_pope_interesting_desc: "Amato dal Papa"
 head_of_faith_interesting_desc: "È un Capo della Fede"
 stronger_than_liege_interesting_desc: "Più Forte del Signore"
 small_king_interesting_desc: "È un Sovrano di un Piccolo Regno"
 can_feudalize_interesting_desc: "Può Feudalizzarsi"
 multiduke_interesting_desc: "Possiede Molti Ducati"
 legitimacy_interesting_desc: "Sovrano Estremamente Legittimo"
 non_dominant_gender_ambitious_char_interesting_desc: "È un Personaggio Ambizioso di Sesso non Dominante"
 non_dominant_gender_ruler_interesting_desc: "È un Sovrano di Sesso non Dominante"
 treacherous_schemer_interesting_desc: "è un Traditore Infido"
 kind_hearted_diplomat_interesting_desc: "È un Diplomatico dal Cuore Gentile"
 different_faith_interesting_desc: "Di Fede Diversa"
 greedy_steward_interesting_desc: "È un Amministratore Avido"
 brazen_commander_interesting_desc: "è un Comandante Sfacciato"
 pious_theologian_interesting_desc: "È un Pio Teologo"
 salacious_seducer_interesting_desc: "è un Salace Seduttore"
 high_skills_desc: "Le Competenze sono Molto Elevate"
 killed_a_lot_interesting_desc: "Uccise più di 10 persone"
 has_both_good_and_bad_genetics_desc: "Ha tratti Genetici sia Buoni che Cattivi"
 good_genetics_desc: "Tratti Genetici Buoni"
 bad_genetics_desc: "Tratti Genetici Cattivi"
 holds_rome_interesting_desc: "Possiede [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Possiede [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Possiede [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Possiede [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Possiede [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Controlla Edifici Speciali"
 has_historical_artifacts_interesting_desc: "Possiede Artefatti Storici Unici"
 underrepresented_faith_interesting_desc: "È di una Fede Sottorappresentata"
 underrepresented_culture_interesting_desc: "È di una Cultura Sottorappresentata"
 outside_realm_desc: "Sovrano Indipendente"
 knows_many_secrets_interesting_desc: "Conosce Molti Segreti"
 has_secrets_interesting_desc: "Ha dei Segreti"
 extremely_wealthy_interesting_desc: "Molto Ricco"
 landless_heir_uninteresting_desc: "Erede del Titolo senza Terra"
 three_virtues_desc: "Ha Tre Virtù"
 three_sins_desc: "Ha tre Peccati"

 skills_difficulty: "Dalle Competenze"
 legitimacy_difficulty: "Dalla Legittimità"
 virtuous_traits_difficulty: "Ha Tratti Virtuosi"
 physique_good_3_difficulty: "È [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 physique_good_2_difficulty: "È [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_1_difficulty: "È [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty: "È [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty: "È [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty: "È [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty: "È [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty: "È [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty: "È [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 shrewd_difficulty: "È [GetTrait('shrewd').GetName( GetNullCharacter )]"
 strong_difficulty: "È [GetTrait('strong').GetName( GetNullCharacter )]"
 sinful_traits_difficulty: "Ha Tratti Peccaminosi"
 incapable_difficulty: "È [GetTrait('incapable').GetName( GetNullCharacter )]"
 leper_difficulty: "È un [GetTrait('leper').GetName( GetNullCharacter )]"
 maimed_difficulty: "È [GetTrait('maimed').GetName( GetNullCharacter )]"
 inbred_difficulty: "È [GetTrait('inbred').GetName( GetNullCharacter )]"
 severely_wounded_difficulty: "È Gravemente Ferito"
 disinherited_difficulty: "È [GetTrait('disinherited').GetName( GetNullCharacter )]"
 sickly_difficulty: "È [GetTrait('sickly').GetName( GetNullCharacter )]"
 poxed_difficulty: "Ha la [GetTrait('great_pox').GetName( GetNullCharacter )]"
 blind_difficulty: "È [GetTrait('blind').GetName( GetNullCharacter )]"
 infirm_difficulty: "È [GetTrait('infirm').GetName( GetNullCharacter )]"
 eunuch_difficulty: "È un [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 lunatic_difficulty: "È un [GetTrait('lunatic').GetName( GetNullCharacter )]"
 murderer_difficulty: "È un [GetTrait('murderer').GetName( GetNullCharacter )]"
 excommunicated_difficulty: "È Scomunicato"
 bleeder_difficulty: "È un [GetTrait('bleeder').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty: "È [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty: "È [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty: "È [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty: "È [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty: "È [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_1_difficulty: "È [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty: "È [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty: "È [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty: "È [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 dull_difficulty: "È [GetTrait('dull').GetName( GetNullCharacter )]"
 weak_difficulty: "È [GetTrait('weak').GetName( GetNullCharacter )]"
 sodomite_difficulty: "È un [GetTrait('sodomite').GetName( GetNullCharacter )]"
 incestuous_difficulty: "È [GetTrait('incestuous').GetName( GetNullCharacter )]"
 fornicator_difficulty: "È un [GetTrait('fornicator').GetName( GetNullCharacter )]"
 adulterer_difficulty: "È un [GetTrait('adulterer').GetName( GetNullCharacter )]"
 cannibal_difficulty: "È un [GetTrait('cannibal').GetName( GetNullCharacter )]"
 witch_difficulty: "È un [GetTrait('witch').GetName( GetNullCharacter )]"
 kinslayer_difficulty: "È un [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 flagellant_difficulty: "È un [GetTrait('flagellant').GetName( GetNullCharacter )]"
 improvident_difficulty: "È [GetTrait('improvident').GetName( GetNullCharacter )]"
 profligate_difficulty: "È [GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty: "È [GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty: "È un [GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty: "È [GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty: "È [GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty: "È [GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty: "È [GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty: "È [GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty: "Ha [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty: "È [GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "È [GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty: "È [GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty: "È [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "È [GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty: "È un [GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty: "Ha un Retaggio Debole"
 comfort_eater_difficulty: "È un [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "È [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty: "È [GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty: "È [GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty: "È [GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty: "È un [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty: "È [GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty: "Ha [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 wounded_difficulty: "È [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty: "È un [GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty: "Ha un difetto di pronuncia [GetTrait('lisping').GetName( GetNullCharacter )]"
 stuttering_difficulty: "È [GetTrait('stuttering').GetName( GetNullCharacter )] Impediment"
 giant_difficulty: "È un [GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty: "Ha [GetTrait('scaly').GetName( GetNullCharacter )]"
 clubfooted_difficulty: "È [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty: "È un [GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty: "È [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty: "È [GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "È [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty: "È un [GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty: "In Guerra"
 losing_war_difficulty: "Guerre Perse"
 faction_difficulty: "Preso di Mira da Fazioni Potenti"
 powerful_neighbors_difficulty: "Potenti Sovrani Vicini"
 military_difficulty: "Forza Militare"
 rivals_difficulty: "Ha Rivali"
 primary_heir_wrong_dynasty_difficulty: "Erede Primario di una Dinastia Sbagliata"
 children_wrong_dynasty_difficulty: "I Figli sono della Dinastia Sbagliata"
 hostile_faith_liege_difficulty: "Signore della Fede Ostile"
 nonpreferred_gender_difficulty: "Genere non Preferito nella Fede"
 wrong_lineality_difficulty: "Linearità Sbagliata nel Matrimonio"
 stress_level_difficulty: "Alto Livello di Stress"
 gold_difficulty: "Ricchezza Eccessiva"
 debt_level_difficulty: "Alto Livello di Debito"
 is_ill_difficulty: "Soffrire di una Mlattia Debilitante"
 imprisoned_difficulty: "Imprigionato"
 elder_difficulty: "Età Avanzata"
 poor_health_difficulty: "Scarsa Salute"
 is_a_vassal_difficulty: "È un Vassallo"
 non_adult_difficulty: "Bambino"
 weak_domain_difficulty: "Dominio Debole"
 unlanded_difficulty: "Non Detiene Titoli"
 
 character_difficulty_text: "Difficoltà: [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "Analisi delle Difficoltà"
 choose_destiny_header_text: "Scegli un Nuovo Destino"
 will_become_adventurer: "Diventerà un [GetGovernment('landless_adventurer_government').GetName]"
 character_interest_breakdown_header: "Aspetti Interessanti"

 different_government_desc: "Ha un Governo Diverso"
 opposite_struggle_faction_desc: "Fazione Opposta in una Lotta"
