l_spanish:
 SETTING_DEBUG_SAVES:0 "Numero dei salvataggi debug"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Suggerimenti Disabilitati"
 #SETTING_FOCUS_ON_COMBAT:1 "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY:1 "Ritardo dei Suggerimenti"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nImposta il ritardo prima della visualizzazione della descrizione."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Sblocca il Ritardo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nImposta il ritardo prima che le Descrizioni siano sbloccate."
 SETTING_TOOLTIP_LOCK_TIME:0 "Blocca il Ritardo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nImposta il ritado prima che le Descrizioni siano bloccate."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Apri quando bloccato"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nImposta il ritardo prima che le Descrizioni siano bloccate quando un'altra è bloccata."
 # Audio
 SETTING_Sound_Effects:1 "Tutti gli Effetti Sonori"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Volume degli effetti sonori\n#!Imposta il volume di tutti gli effetti sonori."
 SETTING_Ambience:0 "Ambiente"
 SETTING_Ambience_TOOLTIP:1 "#T Volume dell'Ambiente\n#!Imposta il volume dell'ambiente circostante."
 SETTING_TOOLTIP_MODE:1 "Modalità dei Suggerimenti"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nImposta il modo in cui i suggerimenti "vengono fissati" abilitando i suggerimenti impilati."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse sul Suggerimento"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nI Suggerimenti si fissano finchè il mouse non viene spostato."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Azione di Blocco"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPremi #V Tasto Centrale del Mouse#! per bloccare e sbloccare i suggerimenti."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Blocco a tempo"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nI suggerimenti vengono fissati se il mouse rimane fermo per un po'. #weak (Default)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Varie"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Suggerimenti"
 SETTINGS_CATEGORY_SFX:0 "Effetti Sonori Specifici"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Generale"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controlli della Mappa"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Salvataggi"
 SETTINGS_CATEGORY_LANGUAGE:0 "Lingua"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Opzioni Avanzate - Generale"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Opzioni Avanzate – Mappa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Opzioni Avanzate – Personaggi"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Ritratti"
 SETTINGS_CATEGORY_GAME_FLAVOR:0 "Flavor"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Multigiocatore"
 SETTINGS_CATEGORY_MAP:0 "Mappa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Mostra le malattie e le ferite"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nDetermina se le ferite e le malattie saranno visibili graficamente nei ritratti dei personaggi."
 SETTING_SHOW_NUDITY:0 "Mostra nudità"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nDetermina se i personaggi possono essere mostrati nudi."
 SETTINGS_CATEGORY_GAME_DLC_MODS:0 "Contenuto Scaricabile"
 SETTING_SHOW_CONTENT_SOURCE:0 "Mostra Evento del DLC"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP:0 "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nImposta se gli Eventi mostrano a quale DLC appartengono." 
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Panoramica Statica Corte Reale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermina se la telecamera della Corte Reale deve fare una leggera panoramica sulla tua Corte quando è inattiva. Se Personaggi Animazioni."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Transizioni Graduali in Corte Reale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermina se la telecamera nella Corte Reale deve spostarsi dolcemente in una nuova posizione. Se "Personaggi Animati" è disattivato, questa impostazione non ha effetto."
 NEVER:0 "Mai"
 MONTHLY:0 "Ogni mese"
 HALFYEAR:0 "Ogni 6 mesi"
 YEARLY:0 "Ogni anno"
 FIVE_YEAR:0 "Ogni 5 anni"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Mostra i consigli reattivi"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nImposta se il gioco deve mostrare i consigli del tutorial che reagiscono al modo in cui giochi. Utile per i nuovi giocatori di Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Mostra Descrizioni"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nImposta se il gioco deve suggerire qualcosa da fare a intervalli regolari. Utile per i nuovi giocatori di Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Reimposta i consigli reattivi"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Reimposta i consigli reattivi#!\nI consigli reattivi visti in precedenza verranno visualizzati di nuovo."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Ripristina l'avviso reattivo"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Sei sicuro di voler ripristinare il consiglio reattivo?"
 SETTING_ADVANCED_SHADERS:0 "Effetti Shader Avanzati"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Effetti Shader Avanzati\n#!Questa opzione abiliterà gli effetti shader avanzati.\n\nDisattivarlo può aumentare le prestazioni al costo di peggiorare la qualità di alcuni effetti (ad esempio il terreno e l'acqua sembrano meno definiti)"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Effetti delle Particelle Invernali"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermina se gli effetti delle particelle vengono mostrati o meno quando l'Inverno è attivo in alcune aree della mappa.\n\nDisattivarlo potrebbe incrementare le prestazioni"
 SETTING_RESET_CAMERA_ROTATION:0 "Ripristino Rotazione Telecamere"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina se la telecamera deve ripristinare automaticamente la posizione di default dopo essere stata ruotata dall'utente."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Inclina Visuale quando Zoom Indietro"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nDetermina se la telecamera deve inclinarsi verso l'inclinazione predefinita quando si esegue lo zoom indietro."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Pers. su Sfondo Scena di Corte"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina se la scena 3D della Corte reale deve mostrare sullo sfondo i personaggi meno importanti."
 SETTING_MAP_HIGHLIGHT:0 "Evidenza del Cursore sulla Mappa"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina l'intensità delle evidenziazioni del cursore sulla mappa"
 BASED_ON_ZOOM_LEVEL:0 "Dinamico"
 ALWAYS_HIDE:0 "Nascondi Sempre"
 ALWAYS_SHOW:0 "Mostra Sempre"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Confini costieri"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nQuesta opzione controllerà quando mostrare i confini dei reami costieri.\nSe $BASED_ON_ZOOM_LEVEL$ quindi saranno nascosti nel livello di zoom dei dettagli.\n\nSelezionando $ALWAYS_SHOW$ o $ALWAYS_HIDE$ si possono aumentare le prestazioni a discapito dei confini del regno costiero che non si nascondono dinamicamente."
 SETTINGS_DISCARD_CHANGES:0 "Annulla Modifiche"
 SETTING_HUD_SKIN:0 "Aspetto dell'HUD"
 hud_skin_auto:0 "Dinamico"
 default:0 "Predefinito"
 iberian:0 "Iberico"
 Norse:0 "Norreno"
 byzantine: "Bizantino"
 iranian:0 "$e_persia_adj$"
 nomad: "$nomad_government$" 
 SETTING_HUD_SKIN_TOOLTIP:0 "#T $SETTING_HUD_SKIN$#!\nImposta il tema visivo dell'interfaccia HUD - l'interfaccia utente 2D visualizzata nella schermata principale del gioco.\n\nSe è stato selezionato $hud_skin_auto$, l'HUD cambierà in base alla cultura, alla fede e alla capitale del regno del giocatore."
 SETTING_RICH_PRESENCE:0 "Presenza Ricca"
 SETTING_RICH_PRESENCE_TOOLTIP:0 "#T $SETTING_RICH_PRESENCE$#!\nMostra agli amici le informazioni sulla sessione di gioco in corso, se la piattaforma lo supporta."
 SETTING_USE_DYNASTY_NAMED_REALMS:0 "Regni Nominati in Base alla Dinastia"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nAlcune culture attribuiscono al titolo principale il nome della loro Dinastia (eg: Abbasidi)."
 map_table_style_auto: "Dinamico"
 map_table_style_western: "Predefinito"
 map_table_style_ce1: "Epidemie"
 map_table_style_ep3: "Bizantina"
 SETTING_MAP_TABLE_STYLE: "Stile Mappa sul Tavolo"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nStabilisce lo stile visivo del tavolo della mappa - la mappa e l'ambiente 3D visualizzati quando si esegue lo zoom indietro.\n\nSe $map_table_style_auto$ viene selezionato, uno stile del tavolo della mappa verrà selezionato in base al Giocatore attuale e al suo personaggio."
 SETTINGS_CATEGORY_STYLING: "Stile dell'Interfaccia"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Grafica Malattie"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nStabilisce se gli effetti delle malattie devono essere mostrati sulla mappa."
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Grafica Leggende"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nStabilisce se gli effetti delle leggende devono essere mostrati sulla mappa."
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED: "Illuminazione Mappa Cartacea"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED_TOOLTIP: "#T $SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED$#!\nStabilisce se la mappa di carta deve ricevere l'illuminazione e le ombre dal tavolo della mappa. (disattiva questa opzione per ottenere la classica colorazione della mappa di carta)"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Icone dettagliate del [raid|e]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nStabilisce se le icone della mappa del [raid|e] debbano mostrare le icone dettagliate o semplificate\n\n#I Se abilitato, tieni premuto Alt per mostare tutti gli insediamenti con bottino da poter [raid|e].#!"
 