l_spanish:
SETTING_REFRACTION:0 "Rifrazione"
SETTING_REFRACTION_QUALITY:0 "Qualità della Rifrazione"
SETTING_MAPOBJECT_QUALITY:0 "Oggetti della Mappa"
SETTING_MAP_SSAO:0 "Mappa SSAO (Occlusione ambientale dello spazio dello schermo)"
SETTING_DOF:0 "Profondità di campo"
SETTING_LENS_FLARE: "Riflesso sull’obbiettivo"
SETTING_SECONDARY_LENS_FLARE: "Riflesso sull’obbiettivo secondario"
