l_spanish: 
# General
SETTING_VALUE_NONE:1 "$VALUE$"
SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
SETTING_VALUE_SECONDS:1 "$VALUE$ secondi"
SETTING_VALUE_MINUTES:0 "$VALUE$ minuti"
# Graphics
SETTING_RENDERER:0 "Renderer"
SETTING_RENDERER_TOOLTIP:0 "Determina quale renderer viene utilizzato."
SETTING_VSYNC:0 "VSync"
SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Fa sì che il gioco e il monitor abbiano la stessa frequenza di fotogrammi, riducendo lo sfarfallio dello schermo.\n\nLa sua disattivazione può aumentare le prestazioni."
SETTING_PORTRAIT_MULTI_SAMPLING:0 "Multicampionamento dei Ritratti"
SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Utilizza il campionamento multiplo per l’Alpha-To-Coverage per rendere più fluida la sfumatura dei capelli.\n\nImpostazioni inferiori aumentano le prestazioni."
SETTING_MULTI_SAMPLING:0 "Anti-aliasing (MSAA)"
SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!L’uso del il campionamento multiplo anti-aliasing (MSAA) rende i bordi delle immagini più uniformi.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_ANTI_ALIASING:0 "Anti-Aliasing"
SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!L'uso dell’anti-aliasing rende i bordi delle immagini più uniformi.\n\nSi consiglia l’uso del FXAA."
OPTION_ANTI_ALIASING_DISABLED:0 "Disabilitato"
OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
SETTING_UPSCALE:0 "Metodo di Ingrandimento"
OPTION_UPSCALE_FSR2:0 "AMD FidelityFX Super Resolution 2"
OPTION_UPSCALE_DLSS:0 "NVIDIA DLSS"
OPTION_UPSCALE_XESS:0 "Intel® XeSS"
SETTING_UPSCALE_QUALITY:0 "Qualità dell’Ingrandimento"
OPTION_UPSCALE_QUALITY_ULTRA_QUALITY:0 "Qualità Ultra"
OPTION_UPSCALE_QUALITY_QUALITY:0 "Qualità"
OPTION_UPSCALE_QUALITY_BALANCED:0 "Equilibrato"
OPTION_UPSCALE_QUALITY_PERFORMANCE:0 "Prestazioni"
OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE:0 "Ultra Performance"
SETTING_ANISOTROPIC_FILTERING:0 "Filtro delle Texture"
SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!L’uso del filtro anisotropico migliora l’aspetto delle texture delle superfici.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_FULLSCREEN_RESOLUTION:0 "Risoluzione a schermo intero"
SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Imposta la qualità dell’immagine del gioco.\n\nRisoluzioni inferiori potrebbero aumentare le prestazioni.\n\n#X La risoluzione del gioco con un rapporto dell’aspetto non supportato potrebbe far apparire le interfacce al di fuori dello schermo.#!"
SETTING_WINDOWED_RESOLUTION:0 "Risoluzione della modalità a finestra"
SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Imposta la risoluzione della finestra di gioco se il gioco è in modalità Finestra.\n\nDeve essere nel formato #b NUMBER#!x#b NUMBER#!.\n\n#X La risoluzione del gioco con un rapporto dell’aspetto non supportato potrebbe far apparire le interfacce al di fuori dello schermo.#!"
SETTING_RENDER_SCALE:0 "Scala di Renderizzazione"
SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nLa scala della risoluzione di rendering del gioco rispetto alla risoluzione principale, esclusa l’interfaccia utente.\n\nLe impostazioni più basse potrebbero aumentare le prestazioni ma ridurre la fedeltà complessiva, mentre superare il 100% potrebbe aumentare la fedeltà ma probabilmente peggiorare le prestazioni."
SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
SETTING_DISPLAY:0 "Schermo"
SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Se il computer disponesse di più schermi, scegli quello che verrà utilizzato dal gioco."
SETTING_GRAPHICS_DEVICE:0 "Scheda Video"
SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleziona la scheda grafica che verrà utilizzata dal gioco. \n\nL’uso di una scheda grafica integrata o di un renderer software potrebbe ridurre le prestazioni."
SETTING_SHADOW_MAP_RESOLUTION:0 "Qualità delle Ombre"
SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina la risoluzione con cui vengono renderizzate le ombre della mappa, se le ombre fossero abilitate.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_DISPLAY_MODE:0 "Modalità dello Schermo"
SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Determina la modalità di visualizzazione del gioco sullo tuo schermo"
SETTING_BLOOM:0 "Bloom" # da verificare Sfocatura della luce
SETTING_MESH_LOD_BIAS:0 "Qualità del LOD (Livello di Dettaglio) delle Mesh"
SETTING_MESH_LOD_FADE:0 "Dissolvenza del LOD (Livello di Dettaglio) delle Mesh"
SETTING_TERRAIN_SMOOTHING:1 "Levigatura del Terreno"
OPTION_FULLSCREEN:0 "Schermo Intero"
OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Visualizza il gioco sull’intero schermo. L’impostazione della Risoluzione modificherà la nitidezza dell’immagine."
OPTION_WINDOWED:0 "Finestra"
OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Visualizza il gioco in una finestra. L’impostazione della Risoluzione modificherà le dimensioni della finestra."
OPTION_DISABLED:1 "Disabilitata" #
OPTION_OFF:0 "Disattivata" #
OPTION_LOW:0 "Bassa" #
OPTION_MEDIUM:0 "Media" #
OPTION_HIGH:0 "Alta" #
OPTION_VERY_HIGH: "Molto Alta"
OPTION_ULTRA:1 "Ultra" #
OPTION_CUSTOM:0 "Personalizzata" #
OPTION_DEFAULT:1 "Predefinita" #
SETTINGS_CATEGORY_UI:0 "Interfaccia"
SETTINGS_CATEGORY_GAME:0 "Gioco"
SETTING_TEXTURE_QUALITY:1 "Qualità delle Texture"
SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nControlla la risoluzione delle texture caricate.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_QUALITY:0 "Qualità Preimpostata"
SETTING_SFX:0 "SFX" # Effetti sonori
SETTING_UI:0 "Interfaccia"
SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Selezionare una preimpostazione delle opzioni grafiche avanzate riportate di seguito.\n\nUna preimpostazione bassa aumenta le prestazioni."
SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Consente di ottenere un effetto "bloom", in cui le luci estremamente luminose si diffondono in altre parti dell’immagine.\n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Abilita la profondità di campo per simulare l’obiettivo di una fotocamera, sfoca i punti fuori fuoco dell’immagine.\n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_LENS_FLARE_TOOLTIP:0 "#T $SETTING_LENS_FLARE$\n#!Abilita l’effetto "lens flare" (riflesso sull’obbiettivo) che appare nelle aree con un elevato effetto "bloom". Affinché l’effetto appaia, è necessario che l’effetto "bloom" sia abilitato. \n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_SECONDARY_LENS_FLARE_TOOLTIP:0 "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Consente di ottenere un effetto di "lens flare" (riflesso sull’obbiettivo) secondario che appare nelle aree con un elevato effetto "bloom". Affinché l’effetto appaia, è necessario che l’effetto "bloom" sia abilitato. \n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Determina se l’occlusione ambientale dello spazio dello schermo debba essere applicata alla mappa.\n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_REFRACTION_TOOLTIP:0 "Determina se le rifrazioni appaiono o meno sull’acqua."
SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nControlla la qualità delle rifrazioni dell’acqua, se fossero abilitate.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina il livello di qualità più alto degli oggetti della mappa (come gli edifici).\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina la qualità dei LOD (Livelli di dettaglio) sugli oggetti della mappa, come i modelli delle unità.\n\nImpostazioni inferiori potrebbero aumentare le prestazioni."
SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Se attivata, i modelli 3D passano in modo fluido da un livello di dettaglio all’altro (LOD) quando si ingrandiscono o si rimpiccioliscono.\n\nLa sua disattivazione potrebbe aumentare le prestazioni."
SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determina il modo in cui i nomi delle Città e delle Province appaiono sulla mappa."
SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determina se il terreno invalicabile sia incluso all’interno dei confini di una nazione sulla mappa."
SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nDetermina la Lingua dell’Interfaccia Utente."
SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "L’email del tuo Account Paradox"
SETTING_FRAMERATE_CAP:1 "FPS Massimi"
SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nGli FPS massimi (Fotogrammi al secondo) che il gioco renderizerà.\n\nImpostazioni inferiori potrebbero ridurre il consumo di energia."
OPTION_CAP_30:0 "30"
OPTION_CAP_60:0 "60"
OPTION_CAP_90:0 "90"
OPTION_CAP_120:0 "120"
OPTION_CAP_144:0 "144"
OPTION_CAP_165:0 "165"
SETTING_TEXTURE_STREAMING:0 "Streaming delle Texture"
SETTING_TEXTURE_STREAMING_TOOLTIP:0 "#T $SETTING_TEXTURE_STREAMING$#!\nLe texture vengono caricate quando necessario.\n\nRiduce l’uso della memoria della GPU al costo di un certo carico di lavoro della CPU. Può aumentare le prestazioni per le GPU con una piccola quantità di memoria."
SETTING_TEXTURE_STREAMING_CACHE:0 "Dimensione della Cache per lo Streaming delle Texture"
SETTING_VALUE_MB:0 "$VALUE$ MB"
# GUI
SETTING_ANIMATION_SPEED:0 "Velocità delle animazioni"
SETTING_GUI_SCALING:0 "Ridimensionamento della GUI"
SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Imposta la scala dell’intera interfaccia utente. Utile per le risoluzioni dello schermo più elevate.\n\n#X Se si impostasse un valore troppo alto, le interfacce non si adatteranno correttamente allo schermo!#!"
# System
SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Panoramica col Mouse"
SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Libera"
SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 direzioni"
SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Disabilitata"
SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nComportamento della telecamera durante la panoramica con il mouse."
SETTING_SCROLL_SPEED:1 "Velocità della Panoramica"
SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nImposta la velocità di spostamento della mappa quando si usa la tastiera o il mouse."
SETTING_CAMERA_ROTATION_SPEED:1 "Velocità di Rotazione della Telecamera"
SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nLa velocità di rotazione della telecamera."
SETTING_ZOOM_SPEED:1 "Velocità dell’Ingrandimento"
SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nLa velocità dell’Ingrandimento della telecamera."
SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Comportamento dell’Ingrandimento"
SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Cursore relativo"
SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Ingrandimento sul cursore"
SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignora il cursore"
SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nComportamento della telecamera rispetto al cursore del mouse durante l’ingrandimento vicino/lontano."
SETTING_INPUT_DEVICE:0 "Dispositivo di input" # da verificare Controlli
SETTING_EDITOR:0 "Editor"
SETTING_EDITOR_POSTFIX:0 "Editor postfix"
SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Comando di apertura dell’Editor"
SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Comando di visualizzazione del registro"
SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Comando di apertura dell’editor del codice"
SETTING_GRACEFUL_EXIT:0 "Uscita di sicurezza"
SETTING_LANGUAGE:0 "Lingua"
MOUSE_AND_KEYBOARD:0 "Mouse e tastiera"
GAMEPAD:0 "Gamepad"
SETTING_MULTISAMPLING_DISABLED:0 "Disabilitato"
SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Disabilitato"
SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Disabilitato"
# Editor
SETTING_CAMERA_TILT:0 "Inclinazione della telecamera"
SETTING_CAMERA_STRATEGY:0 "Tipo di telecamera"
SETTING_CENTERED_ZOOM_IN:0 "Zoom centrato" # Centrato sullo zoom
SETTING_CAMERA_SPEED:0 "Velocità della telecamera"
CAMERA_TABLETOP:0 "Piano del Tavolo"
CAMERA_FPS:0 "Prima persona"
CAMERA_WASD:0 "Stile WASD"
# Audio
SETTING_Music:0 "Musica"
SETTING_Ambient:0 "Ambiente"
SETTING_Effects:0 "Effetti"
SETTING_Master:0 "Generale" # da verificare Volume principale
SETTING_VO:0 "Voce fuori campo"
SETTING_VO_TOOLTIP:0 "#T Volume della voce fuori campo\n#!Imposta il volume dell’audio della voce fuori campo nel gioco."
SETTING_Master_TOOLTIP:0 "#T Volume Generale\n#!Imposta il volume di tutti i suoni nel gioco."
SETTING_Music_TOOLTIP:0 "#T Volume della Musica\n#!Imposta il volume della musica."
SETTING_Ambient_TOOLTIP:0 "#T Volume Ambientale\n#!Imposta il volume dei suoni ambientali."
SETTING_SFX_TOOLTIP:0 "#T SFX Volume\n#!Imposta il volume degli effetti sonori, come quelli dei combattimenti."
SETTING_UI_TOOLTIP:0 "#T Volume Interfaccia\n#!Imposta il volume dell’interfaccia utente."
SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Debug Log Level"
SETTING_AUDIO_DEVICE_PROFILE:0 "Profilo Audio"
SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Seleziona il profilo audio più adatto alla tua configurazione."
SETTING_AUDIO_OPTION_SPEAKERS:0 "Altoparlanti"
SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mix predefinito per il $SETTING_AUDIO_OPTION_SPEAKERS$."
SETTING_AUDIO_OPTION_HEADPHONES:0 "Cuffie"
SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix regolato per le $SETTING_AUDIO_OPTION_HEADPHONES$."
SETTING_AUDIO_OPTION_TV:0 "TV"
SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix per la $SETTING_AUDIO_OPTION_TV$ e per gli altoparlanti per il monitor."
SETTING_AUDIO_OPTION_NIGHTMODE:0 "Modalità Notturna"
SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Attenua il suono per la riproduzione notturna, smorzando le tonalità più alte e comprimendo la gamma dinamica."
SETTING_MUSIC_DENSITY:0 "Densità musicale"
SETTING_MUSIC_DENSITY_TOOLTIP:0 "Controlla il bilanciamento tra i brani completi, il silenzio e i segmenti della musica d’atmosfera.\n\nIntenso = La maggior parte delle canzoni viene riprodotta una dopo l’altra, come una "stazione radio".\nBilanciato = Il perfetto equilibrio tra canzoni, silenzio e atmosfera\nRilassato = Segmenti musicali prevalentemente rilassanti che offrono un’esperienza di una miglior atmosfera e un minor senso di ripetizione dopo diverse ore di riproduzione."
# Game
SETTING_AUTOSAVE:0 "Intervallo del salvataggio automatico"
SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Imposta la frequenza di salvataggio automatico del gioco."
SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determina se i salvataggi automatici verrano salvati o meno nel cloud."
SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determina se la telecamera sarà sempre rivolta verso Nord o meno."
NO_AUTOSAVE:0 "Nessun Salvataggio automatico"
# Multiplayer
SETTINGS_FILE_TRANSFER_SPEED:0 "Velocità di trasferimento dei file"
SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $Velocità di trasferimento dei file$\n#!Imposta la velocità massima per il trasferimento dei file di salvataggio nella Lobby Multigiocatore.\n\nImpostazioni inferiori potrebbero migliorare la stabilità della rete nelle partite multigiocatore, ma hanno un effetto negativo sui tempi di caricamento del multigiocatore."
# Tools
SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Salvataggio automatico dell’editor della mappa (minuti)"
SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Intervallo di salvataggio automatico dell’editor della mappa (minuti)"
SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Node Editor Drag Pan Mode"
SETTING_CONSOLE_AUTOCOMPLETE_MODE:0 "Console auto-complete mode"
SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND:0 "Full expand, iterate with tab"
SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND:0 "Partial expand until different"
# Accessibility
SETTINGS_CATEGORY_ACCESSIBILITY:0 "Accessibilità"
SETTING_COLOR_BLIND_MODE:0 "Modalità per daltonici"
SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Cambia i colori usati nel testo in tutto il gioco in un gruppo di colori che è più facile da distinguere per diversi tipi di daltonismo."