l_spanish: 
 message_settings_tab_settings: "Impostazioni"
 message_settings_tab_log: "Registro Messaggi"
 MESSAGE_SETTINGS_WINDOW_NAME: "Impostazioni Messaggi"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Clicca per aprire le Impostazioni Messaggi#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nModifica la frequenza e la visibilità dei messaggi per gruppi filtrati."
 MESSAGE_SETTINGS_WINDOW_RESET: "Ripristina ai valori predefiniti"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Ripristina Impostazioni Messaggi#!\n#I Clicca per ripristinare le attuali modifiche alle Impostazioni Predefinite#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Applica Modifiche"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Clicca per chiudere la finestra Impostazioni Messaggi e salva le attuali modifiche.#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Notizie" #tradurre
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Notifiche"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Mai"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Filtra Gruppo"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Name of the message filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Appearance"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "How to display messages of this filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "If game should pause when messages of this filter appear"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Toggle Auto-Pause#!\n#I Toggle to pause the game when messages of this filter appear#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Dismiss Message#!\n#I Click to dismiss the current message and show the next message in the queue#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Custom Message"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Custom Message#!\n#I Click to write a custom message to yourself and select when you want to receive it#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Arrival Date: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Title:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Description:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Discard"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Discard Message#!\n#I Click to discard current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Send"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Send#!\n#I Click to send current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Day"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Month"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Year"
