l_spanish:
 message_settings_tab_settings: "Impostazioni"
 message_settings_tab_log: "Registro Messaggi"

 MESSAGE_SETTINGS_WINDOW_NAME: "Impostazioni Messaggi"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Clicca per aprire le Impostazioni dei Messaggi#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nModifica la frequenza e la visibilità dei messaggi per gruppi filtrati."
 MESSAGE_SETTINGS_WINDOW_RESET: "Ripristina ai valori predefiniti"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Ripristina Impostazioni Messaggi#!\n#I Clicca per ripristinare le attuali modifiche alle Impostazioni Predefinite#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Applica Modifiche"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Clicca per chiudere la finestra Impostazioni dei Messaggi e salva le attuali modifiche.#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Notizie"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Notifiche"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Finestra Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Mai"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Filtra Gruppo"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nome del gruppo filtro dei messaggi"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Aspetto"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Come visualizzare i messaggi di questo gruppo filtro"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pausa"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Se il gioco deve andare in pausa quando compaiono messaggi di questo gruppo filtro"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Attiva/Disattiva Pausa Automatica#!\n#I Attiva/Disattiva per mettere in pausa il gioco quando compaiono messaggi di questo gruppo filtro#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Chiudi Messaggio#!\n#I Clicca per chiudere il messaggio attuale e mostrare il successivo in coda#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Messaggio Personalizzato"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Messaggio Personalizzato#!\n#I Clicca per scrivere un messaggio personalizzato a te stesso e selezionare quando riceverlo#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Data di Arrivo: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Titolo:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Descrizione:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Scarta"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Scarta Messaggio#!\n#I Clicca per scartare il messaggio attuale#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Invia"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Invia#!\n#I Clicca per inviare il messaggio attuale#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Giorno"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Mese"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Anno"
